import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  createPublishedReleaseManifest,
  verifyPublishedFunctionArtifact,
  validatePublishedReleaseManifest,
} from "../release-artifact.mjs";

const SHA = "80202fad19521feb5b3ad291a4eb843ee030fb0f";
const DIGEST = `sha256:${"a".repeat(64)}`;
const ACTIVE_CONSENT = "VBT-PD-02/2026.08/01";

async function writeWebArtifact(
  directory,
  { enabled, consentRelease = ACTIVE_CONSENT } = {},
) {
  const webDirectory = join(directory, "web");
  await mkdir(join(webDirectory, "en"), { recursive: true });
  const html = `<!doctype html><html><head><meta name="vbtech-release-sha" content="${SHA}"></head><body><form data-submission-enabled="${String(enabled)}" data-consent-id="${consentRelease}"></form></body></html>`;
  await writeFile(join(webDirectory, "index.html"), html);
  await writeFile(join(webDirectory, "en", "index.html"), html);
  return webDirectory;
}

test("creates a strict disabled release manifest from the generated web identity", async () => {
  const directory = await mkdtemp(join(tmpdir(), "vbtech-release-"));
  const functionPath = join(directory, "vbtech-contact-function.zip");
  await writeFile(functionPath, "function artifact");
  const webDirectory = await writeWebArtifact(directory, { enabled: false });

  const manifest = await createPublishedReleaseManifest({
    releaseSha: SHA,
    publishRunId: "123456789",
    imageTag: `ghcr.io/thevladbog/vbtech-web:${SHA}-disabled`,
    imageDigest: DIGEST,
    functionPath,
    webDirectory,
  });

  assert.equal(manifest.releaseSha, SHA);
  assert.equal(manifest.image.digest, DIGEST);
  assert.equal(manifest.function.name, "vbtech-contact-function.zip");
  assert.match(manifest.function.sha256, /^[0-9a-f]{64}$/);
  assert.deepEqual(manifest.contact, {
    submissionState: "disabled",
    consentRelease: ACTIVE_CONSENT,
  });
  assert.deepEqual(
    validatePublishedReleaseManifest(manifest, {
      expectedReleaseSha: SHA,
      expectedPublishRunId: "123456789",
    }),
    manifest,
  );
  await assert.doesNotReject(() =>
    verifyPublishedFunctionArtifact(manifest, functionPath),
  );

  await writeFile(functionPath, "substituted function artifact");
  await assert.rejects(
    () => verifyPublishedFunctionArtifact(manifest, functionPath),
    /published_function_digest_mismatch/,
  );
});

test("creates an enabled manifest only from matching ACTIVE generated bytes", async () => {
  const directory = await mkdtemp(join(tmpdir(), "vbtech-release-"));
  const functionPath = join(directory, "vbtech-contact-function.zip");
  await writeFile(functionPath, "function artifact");
  const webDirectory = await writeWebArtifact(directory, { enabled: true });

  const manifest = await createPublishedReleaseManifest({
    releaseSha: SHA,
    publishRunId: "123456789",
    imageTag: `ghcr.io/thevladbog/vbtech-web:${SHA}-enabled`,
    imageDigest: DIGEST,
    functionPath,
    webDirectory,
  });

  assert.deepEqual(manifest.contact, {
    submissionState: "enabled",
    consentRelease: ACTIVE_CONSENT,
  });

  const draftWebDirectory = await writeWebArtifact(directory, {
    enabled: true,
    consentRelease: "VBT-PD-02/DRAFT",
  });
  await assert.rejects(
    () =>
      createPublishedReleaseManifest({
        releaseSha: SHA,
        publishRunId: "123456789",
        imageTag: `ghcr.io/thevladbog/vbtech-web:${SHA}-enabled`,
        imageDigest: DIGEST,
        functionPath,
        webDirectory: draftWebDirectory,
      }),
    /invalid_published_release_manifest/,
  );
});

test("rejects mutable, inconsistent, unexpected, or cross-run release metadata", () => {
  const valid = {
    schemaVersion: 1,
    releaseSha: SHA,
    publishRunId: "123456789",
    image: {
      repository: "ghcr.io/thevladbog/vbtech-web",
      tag: `ghcr.io/thevladbog/vbtech-web:${SHA}-disabled`,
      digest: DIGEST,
    },
    function: {
      name: "vbtech-contact-function.zip",
      sha256: "b".repeat(64),
    },
    contact: {
      submissionState: "disabled",
      consentRelease: "VBT-PD-02/DRAFT",
    },
  };

  assert.throws(
    () => validatePublishedReleaseManifest({ ...valid, releaseSha: "latest" }),
    /invalid_published_release_manifest/,
  );
  assert.throws(
    () =>
      validatePublishedReleaseManifest({
        ...valid,
        image: {
          ...valid.image,
          tag: `ghcr.io/thevladbog/vbtech-web:${SHA}-enabled`,
        },
      }),
    /invalid_published_release_manifest/,
  );
  assert.throws(
    () =>
      validatePublishedReleaseManifest({
        ...valid,
        contact: { ...valid.contact, submissionState: "preview" },
      }),
    /invalid_published_release_manifest/,
  );
  assert.throws(
    () =>
      validatePublishedReleaseManifest({
        ...valid,
        contact: {
          submissionState: "enabled",
          consentRelease: "VBT-PD-02/DRAFT",
        },
      }),
    /invalid_published_release_manifest/,
  );
  assert.throws(
    () => validatePublishedReleaseManifest({ ...valid, extra: true }),
    /invalid_published_release_manifest/,
  );
  assert.throws(
    () =>
      validatePublishedReleaseManifest(valid, {
        expectedReleaseSha: SHA,
        expectedPublishRunId: "987654321",
      }),
    /published_release_identity_mismatch/,
  );
});
